---
- name: Install requirements
  zypper:
    name: "{{ cefs_packages }}"
    state: present
  become: true
  when: setup_cefs or setup_defs

# TODO: Download errata-import scripts
# TODO: Create script and cronjob (additional parameters such as
#       channels to include?)
