---
# tasks file for ansible-uyuni

- include_tasks: "check.yml"
  tags: prepare

- include_tasks: "prepare_{{ ansible_distribution | regex_replace(' ', '_') | lower }}.yml"
  tags: prepare

- include_tasks: prepare.yml
  tags: prepare

- include_tasks: install.yml
  tags: install

- include_tasks: content.yml
  tags: content
