---
- name: Check system registration
  command: SUSEConnect --status
  changed_when: false
  register: scc_registration
  when: scc_check_registration or scc_check_modules
  become: true

- name: Register system
  command: "SUSEConnect -r {{ scc_reg_code }} -e {{ scc_mail }}"
  when:
    - scc_check_registration
    - 'scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    - query_filter: "[?identifier == 'SUSE-Manager-Server'].status"
  become: true

- name: Enable modules
  command: "SUSEConnect -p {{ item.identifier }}"
  loop: "{{ sles_modules }}"
  when:
    - scc_check_modules
    - 'scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    - query_filter: "[?identifier == '{{ item.name }}'].status"
  become: true