---
- name: Update system
  zypper:
    name: "*"
    state: latest
  become: true
- name: Install LVM and other core utilities
  zypper:
    name: "{{ core_packages }}"
    state: present
  become: true

- name: Add Uyuni repository
  zypper_repository:
    repo: "{{ uyuni_repo }}"
    name: uyuni-server-stable
    auto_import_keys: true
  become: true
  when: use_uyuni_repo | bool

- name: Create a volume group for Uyuni
  lvg:
    vg: "{{ vg_uyuni }}"
    pvs: "{{ pv_uyuni }}"
  become: true
  when: use_lvm | bool
- name: Createl logical volumes, file systems and mount points
  block:
    - name: Create logical volumes
      lvol:
        vg: "{{ vg_uyuni }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
    - name: Create file systems
      filesystem:
        fstype: "{{ item.type }}"
        dev: "/dev/mapper/{{ vg_uyuni }}-{{ item.name }}"
    - name: Create mount points
      mount:
        path: "{{ item.mountpoint }}"
        src: "/dev/mapper/{{ vg_uyuni }}-{{ item.name }}"
        fstype: "{{ item.type }}"
        opts: auto
        state: mounted
  become: true
  when: use_lvm | bool
  with_items: "{{ filesystems }}"
