---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install python for Ansible
      raw: zypper --non-interactive install python-xml
      become: true
      changed_when: false
    - debug:
        msg: "Ohai"
